export const categories = [
  {
    name: "Postres",
    active: true,
  },
  {
    name: "Tortas",
    active: true,
  },
];

export const products = [
  {
    name: "Torta Negra Tradicional",
    slug: "torta-negra-tradicional",
    description: "La receta original de Fanny, rica en frutas y especias",
    ingredients:
      "Harina, huevos, mantequilla, frutas secas, especias tradicionales",
    price: 50000,
    // categoryId: ,
    stock: 10,
    featured: true,
    active: true,
    images: ["img/MG_0001.webp", "img/MG_9983.jpg", "img/MG_9931.webp"],
  },
  {
    name: "Torta de Chocolate",
    slug: "torta-de-chocolate",
    description: "Deliciosa torta con chocolate belga premium",
    ingredients: "Chocolate belga, harina, huevos, mantequilla, azúcar",
    price: 45000,
    // categoryId: reposteria.id,
    stock: 15,
    featured: true,
    active: true,
    images: ["img/MG_0276.webp", "img/MG_0278.webp", "img/MG_9931.webp"],
  },
  {
    name: "Torta de Vainilla",
    slug: "torta-de-vainilla",
    description: "Suave y esponjosa con vainilla natural",
    ingredients: "Vainilla natural, harina, huevos, mantequilla, leche",
    price: 42000,
    // categoryId: reposteria.id,
    stock: 12,
    featured: true,
    active: true,
    images: ["img/MG_0278.webp", "img/MG_9966.webp", "img/MG_9964.webp"],
  },
  {
    name: "Red Velvet",
    slug: "red-velvet",
    description: "El clásico americano con toque artesanal",
    ingredients: "Cacao, colorante natural, queso crema, harina, mantequilla",
    price: 48000,
    // categoryId: reposteria.id,
    stock: 0,
    featured: true,
    active: true,
    images: ["img/MG_0440.webp", "img/MG_9989.webp", "img/MG_9999.webp"],
  },
  {
    name: "Pan Artesanal Integral",
    slug: "pan-artesanal-integral",
    description: "Pan 100% integral con semillas",
    ingredients:
      "Harina integral, semillas de girasol, chía, linaza, levadura natural",
    price: 8000,
    // categoryId: panaderia.id,
    stock: 20,
    featured: false,
    active: true,
    images: ["img/MG_9890.webp", "img/MG_9953.webp", "img/MG_9960.webp"],
  },
  {
    name: "Croissants de Mantequilla",
    slug: "croissants-de-mantequilla",
    description: "Croissants franceses con mantequilla artesanal",
    ingredients: "Mantequilla artesanal, harina francesa, levadura, sal marina",
    price: 12000,
    // categoryId: panaderia.id,
    stock: 25,
    featured: false,
    active: true,
    images: ["img/MG_9907.webp", "img/MG_9914.webp", "img/MG_9916.webp"],
  },
];
